tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_changetracking: true
    sensiolabs_security_checker: true
    php_mess_detector: true
    php_code_coverage: true
    external_code_coverage:
        timeout: 1800
    php_code_sniffer:
        enabled: true
        config:
            standard: "PSR2"
    php_cpd:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_loc:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
